language: php
php:
  - hhvm
  - nightly
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2

before_script:
  - pear install package.xml
  - pear version
  - pear list

script: phpunit --configuration phpunit.xml

notifications:
  email: false